### ISSUE TITLE
Ideally, notebook operators should run in a fresh Docker image

### ISSUE THREAD

**Issue by dgrtwo** [chriscardillo/gusty-demo#15]
They could use a DockerOperator for this, which would ensure each notebook has a clean environment.

The main reason we're not doing this right away is that Airflow is running in a docker container itself, and putting containers within containers has led to some technical issues (for starters, docker has to be installed).

**Comment by chriscardillo** [comment]
I think this is better suited for an Airflow provider package which includes operators that render notebooks. Should that package come into existence, I'd happily add it to the demo!
