### ISSUE TITLE
Operator to render a python .Rmd file via jupytext

### ISSUE THREAD

**Issue by machow** [chriscardillo/gusty-demo#6]
https://github.com/mwouts/jupytext

https://nbconvert.readthedocs.io/en/latest/

should be able to do something in shell like

```
jupytext --to py target_file.Rmd && python target_file.py
```

**target_file.Rmd:**

``````
---
operator: JupytextRmdOperator
---

```{python}
1 + 1
```
``````

(or could specify operator in another way; could allow parameterization in Rmd files via papermill, etc..)

**Comment by chriscardillo** [comment]
See JupyterOperator!

Expects `.ipynb` target file.

Uses `'(jupyter nbconvert --to script --execute --stdout %s | python)'%(file, )` instead.

Gets params from a yaml markdown cell in the .ipynb targetfile. e.g:

```
    ```yaml
operator: JupyterOperator
dependencies:
    - baby_names
    ```
```
